# Generated by Django 5.2.8 on 2025-11-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_joined_date_member_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='doc',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='pokemon_fav',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
