# Generated by Django 5.2.8 on 2025-11-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_doc_member_gender_member_pokemon_fav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
